//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CONGVIEC
    {
        public int MACONGVIEC { get; set; }
        public string TENCONGVIEC { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string NGUOITHUCHIEN { get; set; }
        public string NGUOIGIAOVIEC { get; set; }
        public string NGUOITHEODOI { get; set; }
        public string DOUUTIEN { get; set; }
        public string LOAICONGVIEC { get; set; }
        public string TIENTRIEN { get; set; }
        public string MOTA { get; set; }
        public byte[] FILEEXP { get; set; }
        public Nullable<int> MANV { get; set; }
    
        public virtual tb_NHANVIEN tb_NHANVIEN { get; set; }
    }
}
